-- Initialisation spécifiques pour un jeu de test
INSERT INTO Galerie(id, nom, adresse) VALUES (1, 'Saatchi', 'King\''s Road, Londres');
INSERT INTO Exposition(id, debut, intitule, duree, organisateur) VALUES (1, LocalDate.of(2020, 1, 1), 'Renaissance', 30, 1);
INSERT INTO Exposition(id, debut, intitule, duree, organisateur) VALUES (2, LocalDate.of(2020, 5, 12), 'Art Moderne', 90, 1);
INSERT INTO Tableau(id, titre, support, largeur, hauteur, auteur) VALUES (1, 'La Joconde', 'Panneau de bois de peuplier', 40, 90, 5);
INSERT INTO Tableau(id, titre, support, largeur, hauteur, auteur) VALUES (2, 'La Naissance de Venus', 'Toile', 170, 280, 6);
INSERT INTO Tableau(id, titre, support, largeur, hauteur, auteur) VALUES (3, 'La Cène', 'Toile', 460, 880, 5);
INSERT INTO Tableau(id, titre, support, largeur, hauteur, auteur) VALUES (4, 'La Nuit Etoilee', 'Peinture à lhuile', 40, 80, 8);
INSERT INTO Tableau(id, titre, support, largeur, hauteur, auteur) VALUES (5, 'Le Baiser', 'Huile sur Toile', 180, 180, 7);
INSERT INTO Tableau(id, titre, support, largeur, hauteur, auteur) VALUES (6, 'Portrait Adele-Bloch Bauer I', 'Huile, Or & Argent sur Toile', 138, 138, 7);
INSERT INTO Transaction(id, venduLe, prixVente, lieuDeVente, client) VALUES (1, LocalDate.of(2020, 1, 16), 180000, 1, 1);
INSERT INTO Transaction(id, venduLe, prixVente, lieuDeVente, client) VALUES (2, LocalDate.of(2020, 1, 27), 66600, 1, 2);
INSERT INTO Transaction(id, venduLe, prixVente, lieuDeVente, client) VALUES (4, LocalDate.of(2020, 6, 21), 8500, 2, 3);
INSERT INTO Transaction(id, venduLe, prixVente, lieuDeVente, client) VALUES (5, LocalDate.of(2020, 6, 24), 700, 2, 4);
INSERT INTO Transaction(id, venduLe, prixVente, lieuDeVente, client) VALUES (6, LocalDate.of(2020, 5, 30), 7500, 2, 3);
INSERT INTO Personne(id, nom, adresse) VALUES (1, 'Oeberg', '2 Kalverstraat, 114 19 Stockholm, Suède');
INSERT INTO Personne(id, nom, adresse) VALUES (2, 'Samuellson', '86 Frescativägen, 114 19 Stockholm, Suède');
INSERT INTO Personne(id, nom, adresse) VALUES (3, 'Boe', 'Rådhusplassen 1, 0037 Oslo, Norvège');
INSERT INTO Personne(id, nom, adresse) VALUES (4, 'Dale', 'Edvard Munchs veg, 2061 Gardermoen, Norvège');
INSERT INTO Personne(id, nom, adresse) VALUES (5, 'Da Vinci', '1 Cours Ferdinand de Lesseps, 92500 Rueil-Malmaison, France');
INSERT INTO Personne(id, nom, adresse) VALUES (6, 'Boticelli', 'Piazza del Colosseo, 1, 00184 Roma RM, Italie');
INSERT INTO Personne(id, nom, adresse) VALUES (7, 'Klimt', 'Klimthaus, Domgasse 5, 1010 Wien, Autriche');
INSERT INTO Personne(id, nom, adresse) VALUES (8, 'Van Gogh', 'Museumplein 6, 1071 DJ Amsterdam, Pays-Bas');
INSERT INTO Artiste(id, biographie) VALUES (5, 'Genie et peintre italien, jai invente pas mal de choses originales comme lhelicoptere');
INSERT INTO Artiste(id, biographie) VALUES (6, 'Peintre de la renaissance principalement connu pour sa peinture de la naissance de la Venus.');
INSERT INTO Artiste(id, biographie) VALUES (7, 'Peintre autrichien, je fais appel à des stratégies originales pour mes peintures. Je peins en utilisant de lor et de largent sur mes toiles.');
INSERT INTO Artiste(id, biographie) VALUES (8, 'Peintre néerlandais, jai loreille coupée mais mes tableaux plaisent après ma mort');